name: dars_test
description: Testing utilities and matchers for the dars package.
version: 0.3.0
repository: https://github.com/kentt8046/dars/blob/main/packages/dars_test/

topics:
  - result-type
  - testing
  - matchers

resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  dars: 0.3.0
  matcher: ^0.12.17
  mockito: ^5.4.5

dev_dependencies:
  test:
