name: dars
description: A Dart-idiomatic Result type package with first-class developer experience.
version: 0.1.0
repository: https://github.com/kentt8046/result_x/blob/main/packages/dars/

topics:
  - result-type
  - error-handling
  - functional-programming

resolution: workspace

environment:
  sdk: ^3.6.0

dev_dependencies:
  coverage:
  test:
